org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
neo_version=21.1.218

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=bountifulrequests
mod_name=Bountiful Requests Addon
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=org.crafterscr

minecraft_version_range=[1.21.1,1.21.2)
neo_version_range=[21.1,)
loader_version_range=[4,)